/**
 * @file Rte_BMS.h
 * @brief AUTOSAR Runtime Environment (RTE) for BMS
 * @author Automotive Agents Team
 * @date 2026-03-19
 *
 * This file would normally be auto-generated by AUTOSAR tools.
 * For this example, it provides simplified RTE interfaces.
 */

#ifndef RTE_BMS_H
#define RTE_BMS_H

#include <stdint.h>
#include <stdbool.h>

/* ======================== RTE Function Prototypes ======================== */

/**
 * @brief Write cell voltages to RTE
 * @param data Pointer to cell monitor data
 */
void Rte_Write_CellVoltages(const void* data);

/**
 * @brief Write pack voltage to RTE
 * @param voltage Pack voltage (0.1V)
 */
void Rte_Write_PackVoltage(uint16_t voltage);

/**
 * @brief Write SOC to RTE
 * @param soc SOC in percent (0-100)
 */
void Rte_Write_SOC(uint8_t soc);

/**
 * @brief Trigger a fault (DTC)
 * @param dtc_code DTC code
 * @param data Associated data
 */
void Rte_TriggerFault(uint16_t dtc_code, uint8_t data);

/**
 * @brief Get system time in milliseconds
 * @return System time (ms)
 */
uint32_t Rte_GetTimeMs(void);

#endif /* RTE_BMS_H */
